# Tools
postgres:
  image: postgres
  ports:
    - "15432:5432"
  volumes_from:
    - 'data'
  environment:
    POSTGRES_USER: "postgres"
    POSTGRES_PASSWORD: "postgres"
data:
  image: busybox
  volumes:
    - ./data:/data
